services:
  tofhir-server:
    image: srdc/tofhir-engine:latest
    container_name: dt4h-tofhir-server
    hostname: tofhir
    command: run --job /usr/local/tofhir/conf/mapping-jobs/cprd/cprd-with-original-structure.json
    environment:
      - FHIR_REPO_URL=http://onfhir:8080/fhir
      - APP_CONF_FILE=/usr/local/tofhir/conf/docker/tofhir-engine.conf
      - FLUENT_HOST=fluentd
      - CONTEXT_PATH=conf
      - JAVA_OPTIONS=-Xms40g -Xmx400g
    ports:
      - "6085:8085"
    networks:
      - tofhir-network
    volumes:
      - './data-ingestion-suite:/usr/local/tofhir/conf'
      - './tofhir-docker-logs:/usr/local/tofhir/logs'
    deploy:
      resources:
        limits:
          cpus: "24.0"
          memory: "410G"
  # Elasticsearch, Fluentd and Kibana stack for mapping job log management
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: dt4h-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx8g"
    ports:
      - "9200:9200"
    networks:
      - tofhir-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  fluentd:
    image: srdc/tofhir-fluentd:latest
    container_name: dt4h-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FORWARD_PORT=24224
      - HOST=elasticsearch
      - PORT=9200
    networks:
      - tofhir-network
  kibana:
    image: srdc/tofhir-kibana:latest
    container_name: dt4h-kibana
    environment:
      - SERVER_BASEPATH=/dt4h/tofhir/kibana
      - SERVER_REWRITEBASEPATH=false
    ports:
      - "5601:5601"
    networks:
      - tofhir-network
    depends_on:
      - elasticsearch
networks:
  tofhir-network:
    name: onfhir-network
    external: true
volumes:
  elasticsearch_data:
    driver: local