services:
  mongo:
    image: mongo:7.0
    container_name: dt4h-mongo
    restart: always
    ports:
      - "6017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - onfhir-network
    volumes:
      - onfhirdata:/data/db
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "2.0"
  #          memory: "8G"
  #        reservations:
  #          cpus: "1.0"
  #          memory: "2G"
  onfhir:
    image: srdc/onfhir:r5
    container_name: dt4h-onfhir
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/fhir/metadata || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - APP_CONF_FILE=/usr/local/onfhir/conf/docker/onfhir-docker.conf
      - FHIR_ROOT_URL=http://onfhir:8080/fhir
      - DB_EMBEDDED=false
      - DB_HOST=mongo:27017
    ports:
      - "6080:8080"
    networks:
      - onfhir-network
    volumes:
      - ./common-data-model:/usr/local/onfhir/conf
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "2.0"
  #          memory: "8G"
  #        reservations:
  #          cpus: "1.0"
  #          memory: "2G"
  tofhir-server:
    image: srdc/tofhir-engine:latest
    container_name: dt4h-tofhir-server
    hostname: tofhir
    command: run --job /usr/local/tofhir/conf/mapping-jobs/cprd/cprd-with-original-structure.json
    environment:
      - FHIR_REPO_URL=http://onfhir:8080/fhir
      - APP_CONF_FILE=/usr/local/tofhir/conf/docker/tofhir-engine.conf
      - FLUENT_HOST=fluentd
      - CONTEXT_PATH=conf
      - JAVA_OPTIONS=-Xms40g -Xmx400g
    ports:
      - "6085:8085"
    networks:
      - onfhir-network
    volumes:
      - './data-ingestion-suite:/usr/local/tofhir/conf'
      - './tofhir-docker-logs:/usr/local/tofhir/logs'
    depends_on:
      onfhir:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: "410G"
  # Elasticsearch, Fluentd and Kibana stack for mapping job log management
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
    container_name: dt4h-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx8g"
    networks:
      - onfhir-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  fluentd:
    image: srdc/tofhir-fluentd:latest
    container_name: dt4h-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - FORWARD_PORT=24224
      - HOST=elasticsearch
      - PORT=9200
    networks:
      - onfhir-network
  kibana:
    image: srdc/tofhir-kibana:latest
    container_name: dt4h-kibana
    environment:
      - SERVER_BASEPATH=/dt4h/tofhir/kibana
      - SERVER_REWRITEBASEPATH=false
    ports:
      - "5601:5601"
    networks:
      - onfhir-network
    depends_on:
      - elasticsearch
networks:
  onfhir-network:
    name: onfhir-network
volumes:
  elasticsearch_data:
    driver: local
  onfhirdata:
    driver: local
